from os import getenv

SECRET_KEY = getenv("SECRET_KEY")
DB_NAME = getenv("DB_NAME")
DB_USERNAME = getenv("DB_USERNAME")
DB_PASSWORD = getenv("DB_PASSWORD")
DB_HOST = getenv("DB_HOST")
DB_PORT = getenv("DB_PORT", "5432")
DATABASE_URL = f"postgresql://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
SUPABASE_SERVICE_KEY = getenv("SUPABASE_SERVICE_KEY")
SUPABASE_URL = getenv("SUPABASE_URL")
SUPABASE_BUCKET_NAME = "student-photos"